set-window-option -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Fix color issues
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Statusbar
set -g @tmux_power_theme 'forest'
set -g @tmux_power_left_a '모 #h'

set -g @tmux_power_right_x '🧇 #{cpu_fg_color} #{cpu_percentage} #{ram_fg_color} #{ram_percentage} #{cpu_temp_fg_color} #{cpu_temp}'
%if "command -v nvidia-smi &>/dev/null || system_profiler SPDisplaysDataType 2>/dev/null | grep -iq 'co-processor'"
  set -g @tmux_power_right_y '👾 #{gpu_fg_color} #{gpu_percentage} #{gram_fg_color} #{gram_percentage} #{gpu_temp_fg_color} #{gpu_temp}'
%else
  set -g @tmux_power_right_y ''
%endif

set -g @tmux_power_right_z '⏳ %T %F'

if "test ! -d ~/.tmux/plugins/tpm" \
     "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
