# BEGIN_KITTY_THEME
# Jet Brains Darcula
include current-theme.conf
# END_KITTY_THEME

Fonts {{{
  font_family               Fira Code
  font_size                 12.0
  font_ltr                  no
  disable_ligatures         never
  narrow_symbols
}}}


